---
version: '3.1'
networks:
  imadethis_public:
    driver: bridge
  imadethis_private:
    driver: bridge
services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=imadethis
      - POSTGRES_PASSWORD=imadethis
    networks:
      - imadethis_private
    ports:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U imadethis']
      interval: 10s
      timeout: 5s
      retries: 5
  migration:
    build: ./server
    environment:
      - FLASK_APP=imadethis_api
      - FLASK_ENV=production
      - IMADETHIS_DB_URI=postgresql://imadethis:imadethis@db:5432/imadethis
    command: flask db upgrade
    depends_on:
      - db
    networks:
      - imadethis_private
    healthcheck:
      test: ['CMD-SHELL', '[ $$(flask db history | wc -l) -eq $$(ls -l migrations/versions/*.py | wc -l) ]']
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: ./server
    restart: always
    environment:
      - FLASK_ENV=production
      - IMADETHIS_DB_URI=postgresql://imadethis:imadethis@db:5432/imadethis
    depends_on:
      - db
      - migration
    networks:
      - imadethis_private
    ports:
      - 5000:5000
    healthcheck:
      test: ['CMD-SHELL', 'curl -L -f http://localhost:5000/health']
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    image: nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - api
    networks:
      - imadethis_public
