---
version: '3.1'
services:
  knock_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: knock_api

  knock_api:
    build: .
    restart: always
    ports:
    link:

#  knock_web:

