---
version: '3.1'
networks:
  knock_public:
    driver: bridge
  knock_private:
    driver: bridge
services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=knock
      - POSTGRES_PASSWORD=knock
    networks:
      - knock_private
    ports:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U knock']
      interval: 10s
      timeout: 5s
      retries: 5
  migration:
    build: .
    environment:
      - FLASK_APP=knock_api
      - FLASK_ENV=production
      - KNOCK_DB_URI=postgresql://knock:knock@db:5432/knock
    command: flask db upgrade
    depends_on:
      - db
    networks:
      - knock_private
    healthcheck:
      test: ['CMD-SHELL', '[ $$(flask db history | wc -l) -eq $$(ls -l migrations/versions/*.py | wc -l) ]']
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: .
    restart: always
    environment:
      - FLASK_ENV=production
      - KNOCK_DB_URI=postgresql://knock:knock@db:5432/knock
    depends_on:
      - db
      - migration
    networks:
      - knock_private
    ports:
      - 5000:5000
    healthcheck:
      test: ['CMD-SHELL', 'curl -L -f http://localhost:5000/health']
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    image: nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - api
    networks:
      - knock_public

