FORMAT: 1A
HOST: http://localhost:5000

# imadethis_api

API for IMadeThis

# Group health

Healthcheck endpoint.

## [/health]

### Check current status [GET]
+ Response 200 (application/json)

        {
            "healthy": true,
            "details": ""
        }

# Group Authentication

Manage accounts and sessions.

## [/auth/register]

### Create a new user account [POST]
+ Request (application/json)

        {
            "username": "TestUser",
            "password": "TestPass",
        }

+ Response 200 (application/json)

        {
            "success": true
        }

## [/auth/login]

### Login to establish a session [POST]
+ Request (application/json)

        {
            "username": "TestUser",
            "password": "TestPass",
        }

+ Response 200 (application/json)

        {
            "access_token": "_JWT_TOKEN_"
        }

## [/auth/active_user]

### Retrieve user information associated with session token [GET]
+ Request
    + Headers

            Authentication: Bearer _JWT_TOKEN_

+ Response 200 (application/json)

        {
            "username": "TestUser",
            "unique_id": "_UUID_"
        }

## [/auth/logout]

### End user session [POST]
+ Request
    + Headers

            Authentication: Bearer _JWT_TOKEN_

+ Response 200 (application/json)

        {"success": true}
