"""empty message

Revision ID: 08f0ccd5c90a
Revises: 
Create Date: 2020-04-04 15:43:07.864541

"""
from alembic import op
import sqlalchemy as sa
import knock_api


# revision identifiers, used by Alembic.
revision = '08f0ccd5c90a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('unique_id', knock_api.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('hashed_pw', sa.String(length=128), nullable=True),
    sa.CheckConstraint('NOT(is_private AND hashed_pw = NULL)', name='private_thread_has_pw'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_thread_date_created'), 'thread', ['date_created'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('unique_id', knock_api.models.GUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_pw', sa.String(length=128), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('thread_membership',
    sa.Column('thread_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('thread_id', 'user_id')
    )
    op.create_index(op.f('ix_thread_membership_date_created'), 'thread_membership', ['date_created'], unique=False)
    op.create_table('thread_message',
    sa.Column('message_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_thread_message_timestamp'), 'thread_message', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_message_timestamp'), table_name='thread_message')
    op.drop_table('thread_message')
    op.drop_index(op.f('ix_thread_membership_date_created'), table_name='thread_membership')
    op.drop_table('thread_membership')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_thread_date_created'), table_name='thread')
    op.drop_table('thread')
    # ### end Alembic commands ###
