"""Initial migration.

Revision ID: 462fc79586ad
Revises: 
Create Date: 2020-03-14 19:04:57.214266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462fc79586ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('thread_membership',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('thread_id', 'username')
    )
    op.create_table('thread_message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_thread_message_timestamp'), 'thread_message', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_message_timestamp'), table_name='thread_message')
    op.drop_table('thread_message')
    op.drop_table('thread_membership')
    op.drop_table('user')
    op.drop_table('thread')
    # ### end Alembic commands ###
